### ISSUE TITLE
Settings Menu not visible in online version

### ISSUE THREAD

**Issue by django23** [SylvainGa/crystal-face#7]
Hi Sylvain,

Great work on the app.
After installing the app, I can't change the settings. I did install the original, and that one works. 
Do you have a tip to help me solve that? It does work through the Desktop Application

Cheers,

![Screenshot_20230325-140503](https://user-images.githubusercontent.com/827397/227718938-9e842705-db45-4890-a03a-6eb4b2a5792b.png)

<img width="623" alt="image" src="https://user-images.githubusercontent.com/827397/227719398-a1df1712-6ae7-424b-91f1-ca416bb03b76.png">

**Comment by django23** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/827397/227719448-c6858275-593d-47d0-9d6b-c6b1546c446e.png">

Actually, the settings are not working through the app either due to an error message

**Comment by SylvainGa** [comment]
Could be a conflict between both watchface? Have you deleted the PixelPathos' version?

**Comment by SylvainGa** [comment]
This was fixed a while ago. Newest version should not experience this problem anymore.
