### ISSUE TITLE
Colon between hours and minutes not centered

### ISSUE THREAD

**Issue by blueberry-bytes** [SylvainGa/crystal-face#9]
When I enable colon between hours and minutes, the text is no longer centered. It can be fixed in file ThickThinTime.mc, line 78 by adding
`dc.getTextWidthInPixels(":", mMinutesFont)`
if colon is enabled.

**Comment by SylvainGa** [comment]
Thanks, I'm currently testing V2.20 and I've added the modification to that code base.
